### ISSUE TITLE
Utility function to quickly find input nodes, if present

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/bw_hestia_bridge#23]
This cycle: https://www-staging.hestia.earth/cycle/s_iwp86ylxhd?dataState=recalculated#impactDriverChart

Consumes one of the outputs of this cycle: https://www-staging.hestia.earth/cycle/ribhbymfmmt3?dataState=recalculated#impactDriverChart

(though one is 2013, one is 2014, I am not sure if there could be another cycle which is more cleanly linked...)

It would be great, when turning the cycle into a process that Brightway can handle, to be able to find these kinds of links by calling the API.

**Comment by tfardet** [comment]
Should be supported via #24  and #26 

```python
search_hestia({"inputs.term.name": the_name})
```

It doesn't work with ``"inputs.term.@id"``, which is annoying but I think that's a bug on Hestia's side.

**Comment by tfardet** [comment]
@cmutel can we close this or did you mean something else that is still not implemented?

**Comment by cswh** [comment]
Here are some more information on how thy cycles are linked within hestia: https://github.com/brightway-lca/bw_hestia_bridge/issues/10#issuecomment-1724002695

The requested utility function is part of that issue. Therefore I will close due to duplicateness.
