### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by tfardet** [brightway-lca/bw_hestia_bridge#25]
Would be good to set up tests for the various functions.

**Comment by cmutel** [comment]
Some of us have been adding tests since the beginning 😛

**Comment by tfardet** [comment]
Yeah, I know ;P
This is mostly as a reminder for me that I should do it...
But maybe it could actually be a good exercise for @cswh or @TimoDiepers  to check that the functions work as they think they should ^^

**Comment by cswh** [comment]
I am trying to deal with issues which are not assigned. Since more tests have been added, I will close this issue.

Feel free to reopen and specify what has to be done.
