### ISSUE TITLE
Map Hestia biosphere flows to ecoinvent

### ISSUE THREAD

**Issue by TimoDiepers** [brightway-lca/bw_hestia_bridge#42]
The biosphere flows need to be mapped to ecoinvent as well.

**Comment by TimoDiepers** [comment]
Shared Mapping Sheet: https://docs.google.com/spreadsheets/d/1plz2oG_jn2tGDiSU0oj3NHTSvTF4FfptSNSz_rjDUpw/edit#gid=379685208

**Comment by cswh** [comment]
Are you working on the mapping of the biosphere flows for the minimal working example @TimoDiepers ? Or shall somebody else look into that and have something working in the code?

**Comment by cswh** [comment]
@TimoDiepers  Feel free to reassign to me, if I shall take care of it...

**Comment by TimoDiepers** [comment]
We have a fairly complete list now, the remaining (~5) flows don‘t seem to have a direct ecoinvent equivalent. If you @cswh want to double check that we havent missed anything, that would be great!

**Comment by cswh** [comment]
Looks good enough to me to be used for milestone https://github.com/brightway-lca/bw_hestia_bridge/milestone/1

Can you include that in our repo @TimoDiepers ?

/unassign @cswh

**Comment by TimoDiepers** [comment]
Included in https://github.com/brightway-lca/bw_hestia_bridge/pull/49/commits/cdd2728f1e8b2adb5632c00546c3abbf42170cb7
