### ISSUE TITLE
Proposed structure for to get data from hestia

### ISSUE THREAD

**Issue by tfardet** [brightway-lca/bw_hestia_bridge#6]
```__init__.py -> _config: dict storing the token 
_hestia_api/
    __init__.py
    query.py
        search_hestia(element: str)
        get_hestia_node(node_id: str)
    credentials.py
        login_to_hestia(email: str, pwd: str)
        set_token(token: str)
utils/
    __init__.py
    version.py
    appdirs.py
```

[appdirs](https://github.com/ActiveState/appdirs/blob/master/appdirs.py) (MIT) is to get folders to store the token and cache requests

I'd propose to load everything from ``_hestia_api`` into the main ``__init__.py``.

**Comment by cmutel** [comment]
Some comments from my side:

* [platformdirs](https://github.com/platformdirs/platformdirs) instead of appdirs
* Completely personal opinion: `_hestia_api` is pretty awkward, maybe these files could be in the main directory, but the starting `_` is going to drive me crazy every time is see it 😛
