### ISSUE TITLE
Hi I am a beginner and I really don't know what the problem is.. the code worked before :(

### ISSUE THREAD

**Issue by Kathleen1203** [brightway-lca/bw_hestia_bridge#64]
imp = bw.ExcelImporter("/Users/kathleenschodorf/Documents/LCA Labor 23-24/Day 2/LCIs_Lithium/Lithium Hombre Muerto_bearbeitet.xlsx")
imp.apply_strategies()
imp.match_database("ecoinvent 3.9.1", fields=('name','unit','location'))
imp.match_database(fields=('imp.write_database()name', 'unit', 'location'))
imp.statistics()

Extracted 1 worksheets in 0.30 seconds
Applying strategy: csv_restore_tuples
Applying strategy: csv_restore_booleans
Applying strategy: csv_numerize
Applying strategy: csv_drop_unknown
Applying strategy: csv_add_missing_exchanges_section
Applying strategy: normalize_units
Applying strategy: normalize_biosphere_categories
Applying strategy: normalize_biosphere_names
Applying strategy: strip_biosphere_exc_locations
Applying strategy: set_code_by_activity_hash
Applying strategy: link_iterable_by_fields
Applying strategy: assign_only_product_as_production
Applying strategy: link_technosphere_by_activity_hash
Applying strategy: drop_falsey_uncertainty_fields_but_keep_zeros
Applying strategy: convert_uncertainty_types_to_integers
Applying strategy: convert_activity_parameters_to_list
Applied 16 strategies in 18.48 seconds
Applying strategy: link_iterable_by_fields
Applying strategy: link_iterable_by_fields
Couldn't apply strategy link_iterable_by_fields:
	Object in source database can't be uniquely linked to target database.
Problematic dataset         is:
{'filename': '(missing)',
 'imp.write_database()name': '(missing)',
 'location': 'AR-HOM',
 'unit': 'kilogram'}
Possible targets include (at least one not shown):
[{'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'},
 {'filename': '(missing)',
  'imp.write_database()name': '(missing)',
  'location': 'AR-HOM',
  'unit': 'kilogram'}]
18 datasets
69 exchanges
41 unlinked exchanges
  Type production: 18 unique unlinked exchanges
  Type technosphere: 16 unique unlinked exchanges
(18, 69, 41)

**Comment by tfardet** [comment]
This does not look like it is related to the bridge: you're not using ``bw_hestia_bridge``, are you? Just regular brightway ?

Just skimming though what you sent, it seems like a bug in your code, you probably deleted a ``.`` by mistake as I see a ``'imp.write_database()name`` entry, which does not look right.
